### ISSUE TITLE
Congratulations AMA Santiago on ARC 2023 Hackathon Challenge

### ISSUE THREAD

**Issue by AnimMouse** [alexisvalentino/Campus-based-WEB-LMS#1]
Congratulations Alexis and Alberto of AMA Santiago for winning 1st place in AMAES Research Congress 2023 Hackathon Challenge with Accenture!

from Shawn and Marc Hanzel of AMA Fairview.

**Comment by alexisvalentino** [comment]
Thank you. Same to you guys! 

Anyways how'd you find out this repo?

**Comment by AnimMouse** [comment]
> Anyways how'd you find out this repo?

Sinearch ko yung pangalan mo sa FB tapos nakita ko yung GitHub account mo, binuksan ko, at ito na nga yung source code sa hackathon, hahahaha.

> Thank you. Same to you guys!

Thank you too!

**Comment by alexisvalentino** [comment]
Galing! That's a Good one. I can make you as a collaborator dito kung gusto mo. I'm planning to improve the site since di sya natapos. Commit ka lang and Push code ko Magkakaroon na agad ng Changes, Naka Devops process kasi talaga yun. Yung changes nya realtime, dahil connected sya dito sa Github Repo. 

Yun lang, message ka sa Fb bro kapag interested ka. I'll close this issue, again congratulations.

**Comment by alexisvalentino** [comment]
Galing! That's a Good one. I can make you as a collaborator dito kung gusto mo. I'm planning to improve the site. Since yung changes nya realtime, (Devops CI/CD). Commit ka lang and push code ko.

Yun lang, message ka sa Fb bro kapag interested ka. I'll close this issue, again congratulations. Contribute ka din sa Open source lalo ka matututo!

**Comment by AnimMouse** [comment]
> Galing! That's a Good one. I can make you as a collaborator dito kung gusto mo. I'm planning to improve the site. Since yung changes nya realtime, (Devops CI/CD). Commit ka lang and push code ko.

Nice, kung may naisip akong improvement dito, mag pu-pull request nalang ako rito.

> Yun lang, message ka sa Fb bro kapag interested ka. I'll close this issue, again congratulations.

Sige, message nalang ako pag may naisip akong gawin dito. Congratulations ulit saatin!

> Contribute ka din sa Open source lalo ka matututo!

Oo nga, marami akong natututunan pag nag co-contribute ako sa open source.
